#!/bin/bash

GAPBS_80GB_GRAPH=${GAPBS_80GB_GRAPH:-${BENCH_ROOT}/gapbs/benchmark/graph-80GB.sg}

WORKLOAD_ID="bc-graph-80GB.sg"
WORKLOAD_OUTPUT="bc-graph-80GB.sg"
WORKLOAD_COMMAND="OMP_NUM_THREADS=16 ${BENCH_ROOT}/gapbs/bc -n 10 -f ${GAPBS_80GB_GRAPH}"
WORKLOAD_EXE_NAME="bc"
WORKLOAD_MODEL_BASE="bc-graph-80GB.sg"
WORKLOAD_VIRTUAL_STEP_SAMPLES="10000"
WORKLOAD_SYSTEMS="arms model logging"
