#!/bin/bash

WORKLOAD_ID="mg.D.x"
WORKLOAD_OUTPUT="mg.D.x"
WORKLOAD_COMMAND="OMP_NUM_THREADS=16 ${BENCH_ROOT}/NPB3.4.3/NPB3.4-OMP/bin/mg.D.x"
WORKLOAD_EXE_NAME="mg.D.x"
WORKLOAD_MODEL_BASE="mg.D.x"
WORKLOAD_SYSTEMS="arms hybridtier model logging"
