#!/bin/bash

GAPBS_80GB_GRAPH=${GAPBS_80GB_GRAPH:-${BENCH_ROOT}/gapbs/benchmark/graph-80GB.sg}

WORKLOAD_ID="pr-graph-80GB.sg"
WORKLOAD_OUTPUT="pr-graph-80GB.sg"
WORKLOAD_COMMAND="OMP_NUM_THREADS=16 ${BENCH_ROOT}/gapbs/pr -n 10 -f ${GAPBS_80GB_GRAPH}"
WORKLOAD_EXE_NAME="pr"
WORKLOAD_MODEL_BASE="pr-graph-80GB.sg"
WORKLOAD_VIRTUAL_STEP_SAMPLES="10000"
WORKLOAD_SYSTEMS="arms model logging"
