#!/bin/bash

WORKLOAD_ID="XSBench"
WORKLOAD_OUTPUT="XSBench"
WORKLOAD_COMMAND="OMP_NUM_THREADS=16 ${BENCH_ROOT}/XSBench/openmp-threading/XSBench -t 16 -g 50000 -p 10000000"
WORKLOAD_EXE_NAME="XSBench"
WORKLOAD_MODEL_BASE="XSBench"
WORKLOAD_VIRTUAL_STEP_SAMPLES="3162"
WORKLOAD_SYSTEMS="arms hybridtier model logging"
